// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: server/grpc/proto/eventstore.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventStore_Append_FullMethodName            = "/eventstore.EventStore/Append"
	EventStore_ReadStream_FullMethodName        = "/eventstore.EventStore/ReadStream"
	EventStore_ReadAll_FullMethodName           = "/eventstore.EventStore/ReadAll"
	EventStore_Health_FullMethodName            = "/eventstore.EventStore/Health"
	EventStore_SubscribeToAll_FullMethodName    = "/eventstore.EventStore/SubscribeToAll"
	EventStore_SubscribeToStream_FullMethodName = "/eventstore.EventStore/SubscribeToStream"
)

// EventStoreClient is the client API for EventStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventStore service definition
type EventStoreClient interface {
	// Append an event to a stream
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// Read all events from a stream (server streaming)
	ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Read all events in global order (server streaming)
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Subscribe to all events (catch-up + live)
	SubscribeToAll(ctx context.Context, in *SubscribeToAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Subscribe to a specific stream (catch-up + live)
	SubscribeToStream(ctx context.Context, in *SubscribeToStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type eventStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStoreClient(cc grpc.ClientConnInterface) EventStoreClient {
	return &eventStoreClient{cc}
}

func (c *eventStoreClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, EventStore_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStore_ServiceDesc.Streams[0], EventStore_ReadStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadStreamRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_ReadStreamClient = grpc.ServerStreamingClient[Event]

func (c *eventStoreClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStore_ServiceDesc.Streams[1], EventStore_ReadAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadAllRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_ReadAllClient = grpc.ServerStreamingClient[Event]

func (c *eventStoreClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, EventStore_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) SubscribeToAll(ctx context.Context, in *SubscribeToAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStore_ServiceDesc.Streams[2], EventStore_SubscribeToAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeToAllRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_SubscribeToAllClient = grpc.ServerStreamingClient[Event]

func (c *eventStoreClient) SubscribeToStream(ctx context.Context, in *SubscribeToStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStore_ServiceDesc.Streams[3], EventStore_SubscribeToStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeToStreamRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_SubscribeToStreamClient = grpc.ServerStreamingClient[Event]

// EventStoreServer is the server API for EventStore service.
// All implementations must embed UnimplementedEventStoreServer
// for forward compatibility.
//
// EventStore service definition
type EventStoreServer interface {
	// Append an event to a stream
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// Read all events from a stream (server streaming)
	ReadStream(*ReadStreamRequest, grpc.ServerStreamingServer[Event]) error
	// Read all events in global order (server streaming)
	ReadAll(*ReadAllRequest, grpc.ServerStreamingServer[Event]) error
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Subscribe to all events (catch-up + live)
	SubscribeToAll(*SubscribeToAllRequest, grpc.ServerStreamingServer[Event]) error
	// Subscribe to a specific stream (catch-up + live)
	SubscribeToStream(*SubscribeToStreamRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedEventStoreServer()
}

// UnimplementedEventStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStoreServer struct{}

func (UnimplementedEventStoreServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedEventStoreServer) ReadStream(*ReadStreamRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method ReadStream not implemented")
}
func (UnimplementedEventStoreServer) ReadAll(*ReadAllRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method ReadAll not implemented")
}
func (UnimplementedEventStoreServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedEventStoreServer) SubscribeToAll(*SubscribeToAllRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToAll not implemented")
}
func (UnimplementedEventStoreServer) SubscribeToStream(*SubscribeToStreamRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToStream not implemented")
}
func (UnimplementedEventStoreServer) mustEmbedUnimplementedEventStoreServer() {}
func (UnimplementedEventStoreServer) testEmbeddedByValue()                    {}

// UnsafeEventStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStoreServer will
// result in compilation errors.
type UnsafeEventStoreServer interface {
	mustEmbedUnimplementedEventStoreServer()
}

func RegisterEventStoreServer(s grpc.ServiceRegistrar, srv EventStoreServer) {
	// If the following call panics, it indicates UnimplementedEventStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStore_ServiceDesc, srv)
}

func _EventStore_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStore_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_ReadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStoreServer).ReadStream(m, &grpc.GenericServerStream[ReadStreamRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_ReadStreamServer = grpc.ServerStreamingServer[Event]

func _EventStore_ReadAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStoreServer).ReadAll(m, &grpc.GenericServerStream[ReadAllRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_ReadAllServer = grpc.ServerStreamingServer[Event]

func _EventStore_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStore_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_SubscribeToAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStoreServer).SubscribeToAll(m, &grpc.GenericServerStream[SubscribeToAllRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_SubscribeToAllServer = grpc.ServerStreamingServer[Event]

func _EventStore_SubscribeToStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStoreServer).SubscribeToStream(m, &grpc.GenericServerStream[SubscribeToStreamRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_SubscribeToStreamServer = grpc.ServerStreamingServer[Event]

// EventStore_ServiceDesc is the grpc.ServiceDesc for EventStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eventstore.EventStore",
	HandlerType: (*EventStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _EventStore_Append_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _EventStore_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadStream",
			Handler:       _EventStore_ReadStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadAll",
			Handler:       _EventStore_ReadAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToAll",
			Handler:       _EventStore_SubscribeToAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToStream",
			Handler:       _EventStore_SubscribeToStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server/grpc/proto/eventstore.proto",
}
