// Code generated by protoc-gen-go. DO NOT EDIT.
// This file was manually created to match eventstore.proto

package proto

// AppendRequest is the request for Append RPC
type AppendRequest struct {
	StreamId        string `json:"stream_id,omitempty"`
	EventId         string `json:"event_id,omitempty"`
	Data            []byte `json:"data,omitempty"`
	ExpectedVersion int64  `json:"expected_version,omitempty"`
}

// AppendResponse is the response for Append RPC
type AppendResponse struct {
	Position int64 `json:"position,omitempty"`
	Version  int64 `json:"version,omitempty"`
}

// ReadStreamRequest is the request for ReadStream RPC
type ReadStreamRequest struct {
	StreamId    string `json:"stream_id,omitempty"`
	FromVersion int64  `json:"from_version,omitempty"`
}

// ReadAllRequest is the request for ReadAll RPC
type ReadAllRequest struct {
	FromPosition int64 `json:"from_position,omitempty"`
}

// Event represents an event in gRPC responses
type Event struct {
	Position int64  `json:"position,omitempty"`
	StreamId string `json:"stream_id,omitempty"`
	Version  int64  `json:"version,omitempty"`
	Data     []byte `json:"data,omitempty"`
}

// HealthRequest is the request for Health RPC
type HealthRequest struct{}

// HealthResponse is the response for Health RPC
type HealthResponse struct {
	Status string `json:"status,omitempty"`
}
