// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: server/grpc/proto/eventstore.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamId        string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	EventId         string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Data            []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_eventstore_proto_rawDescGZIP(), []int{0}
}

func (x *AppendRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AppendRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AppendRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppendRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int64                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_eventstore_proto_rawDescGZIP(), []int{1}
}

func (x *AppendResponse) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *AppendResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ReadStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	FromVersion   int64                  `protobuf:"varint,2,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"` // 0 means from beginning
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStreamRequest) Reset() {
	*x = ReadStreamRequest{}
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamRequest) ProtoMessage() {}

func (x *ReadStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamRequest.ProtoReflect.Descriptor instead.
func (*ReadStreamRequest) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_eventstore_proto_rawDescGZIP(), []int{2}
}

func (x *ReadStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ReadStreamRequest) GetFromVersion() int64 {
	if x != nil {
		return x.FromVersion
	}
	return 0
}

type ReadAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPosition  int64                  `protobuf:"varint,1,opt,name=from_position,json=fromPosition,proto3" json:"from_position,omitempty"` // 0 means from beginning
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllRequest) Reset() {
	*x = ReadAllRequest{}
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllRequest) ProtoMessage() {}

func (x *ReadAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllRequest.ProtoReflect.Descriptor instead.
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_eventstore_proto_rawDescGZIP(), []int{3}
}

func (x *ReadAllRequest) GetFromPosition() int64 {
	if x != nil {
		return x.FromPosition
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int64                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_eventstore_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Event) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Event) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_eventstore_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_eventstore_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubscribeToAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPosition  int64                  `protobuf:"varint,1,opt,name=from_position,json=fromPosition,proto3" json:"from_position,omitempty"` // 0 means from beginning
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToAllRequest) Reset() {
	*x = SubscribeToAllRequest{}
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToAllRequest) ProtoMessage() {}

func (x *SubscribeToAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToAllRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToAllRequest) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_eventstore_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeToAllRequest) GetFromPosition() int64 {
	if x != nil {
		return x.FromPosition
	}
	return 0
}

type SubscribeToStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	FromVersion   int64                  `protobuf:"varint,2,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"` // 0 means from beginning
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToStreamRequest) Reset() {
	*x = SubscribeToStreamRequest{}
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToStreamRequest) ProtoMessage() {}

func (x *SubscribeToStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_eventstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToStreamRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToStreamRequest) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_eventstore_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeToStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *SubscribeToStreamRequest) GetFromVersion() int64 {
	if x != nil {
		return x.FromVersion
	}
	return 0
}

var File_server_grpc_proto_eventstore_proto protoreflect.FileDescriptor

const file_server_grpc_proto_eventstore_proto_rawDesc = "" +
	"\n" +
	"\"server/grpc/proto/eventstore.proto\x12\n" +
	"eventstore\"\x86\x01\n" +
	"\rAppendRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\"F\n" +
	"\x0eAppendResponse\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x03R\bposition\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"S\n" +
	"\x11ReadStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12!\n" +
	"\ffrom_version\x18\x02 \x01(\x03R\vfromVersion\"5\n" +
	"\x0eReadAllRequest\x12#\n" +
	"\rfrom_position\x18\x01 \x01(\x03R\ffromPosition\"n\n" +
	"\x05Event\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x03R\bposition\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"<\n" +
	"\x15SubscribeToAllRequest\x12#\n" +
	"\rfrom_position\x18\x01 \x01(\x03R\ffromPosition\"Z\n" +
	"\x18SubscribeToStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12!\n" +
	"\ffrom_version\x18\x02 \x01(\x03R\vfromVersion2\xa6\x03\n" +
	"\n" +
	"EventStore\x12?\n" +
	"\x06Append\x12\x19.eventstore.AppendRequest\x1a\x1a.eventstore.AppendResponse\x12@\n" +
	"\n" +
	"ReadStream\x12\x1d.eventstore.ReadStreamRequest\x1a\x11.eventstore.Event0\x01\x12:\n" +
	"\aReadAll\x12\x1a.eventstore.ReadAllRequest\x1a\x11.eventstore.Event0\x01\x12?\n" +
	"\x06Health\x12\x19.eventstore.HealthRequest\x1a\x1a.eventstore.HealthResponse\x12H\n" +
	"\x0eSubscribeToAll\x12!.eventstore.SubscribeToAllRequest\x1a\x11.eventstore.Event0\x01\x12N\n" +
	"\x11SubscribeToStream\x12$.eventstore.SubscribeToStreamRequest\x1a\x11.eventstore.Event0\x01B-Z+github.com/hydra-db/hydra/server/grpc/protob\x06proto3"

var (
	file_server_grpc_proto_eventstore_proto_rawDescOnce sync.Once
	file_server_grpc_proto_eventstore_proto_rawDescData []byte
)

func file_server_grpc_proto_eventstore_proto_rawDescGZIP() []byte {
	file_server_grpc_proto_eventstore_proto_rawDescOnce.Do(func() {
		file_server_grpc_proto_eventstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_grpc_proto_eventstore_proto_rawDesc), len(file_server_grpc_proto_eventstore_proto_rawDesc)))
	})
	return file_server_grpc_proto_eventstore_proto_rawDescData
}

var file_server_grpc_proto_eventstore_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_server_grpc_proto_eventstore_proto_goTypes = []any{
	(*AppendRequest)(nil),            // 0: eventstore.AppendRequest
	(*AppendResponse)(nil),           // 1: eventstore.AppendResponse
	(*ReadStreamRequest)(nil),        // 2: eventstore.ReadStreamRequest
	(*ReadAllRequest)(nil),           // 3: eventstore.ReadAllRequest
	(*Event)(nil),                    // 4: eventstore.Event
	(*HealthRequest)(nil),            // 5: eventstore.HealthRequest
	(*HealthResponse)(nil),           // 6: eventstore.HealthResponse
	(*SubscribeToAllRequest)(nil),    // 7: eventstore.SubscribeToAllRequest
	(*SubscribeToStreamRequest)(nil), // 8: eventstore.SubscribeToStreamRequest
}
var file_server_grpc_proto_eventstore_proto_depIdxs = []int32{
	0, // 0: eventstore.EventStore.Append:input_type -> eventstore.AppendRequest
	2, // 1: eventstore.EventStore.ReadStream:input_type -> eventstore.ReadStreamRequest
	3, // 2: eventstore.EventStore.ReadAll:input_type -> eventstore.ReadAllRequest
	5, // 3: eventstore.EventStore.Health:input_type -> eventstore.HealthRequest
	7, // 4: eventstore.EventStore.SubscribeToAll:input_type -> eventstore.SubscribeToAllRequest
	8, // 5: eventstore.EventStore.SubscribeToStream:input_type -> eventstore.SubscribeToStreamRequest
	1, // 6: eventstore.EventStore.Append:output_type -> eventstore.AppendResponse
	4, // 7: eventstore.EventStore.ReadStream:output_type -> eventstore.Event
	4, // 8: eventstore.EventStore.ReadAll:output_type -> eventstore.Event
	6, // 9: eventstore.EventStore.Health:output_type -> eventstore.HealthResponse
	4, // 10: eventstore.EventStore.SubscribeToAll:output_type -> eventstore.Event
	4, // 11: eventstore.EventStore.SubscribeToStream:output_type -> eventstore.Event
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_grpc_proto_eventstore_proto_init() }
func file_server_grpc_proto_eventstore_proto_init() {
	if File_server_grpc_proto_eventstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_grpc_proto_eventstore_proto_rawDesc), len(file_server_grpc_proto_eventstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_grpc_proto_eventstore_proto_goTypes,
		DependencyIndexes: file_server_grpc_proto_eventstore_proto_depIdxs,
		MessageInfos:      file_server_grpc_proto_eventstore_proto_msgTypes,
	}.Build()
	File_server_grpc_proto_eventstore_proto = out.File
	file_server_grpc_proto_eventstore_proto_goTypes = nil
	file_server_grpc_proto_eventstore_proto_depIdxs = nil
}
