// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This file was manually created to match eventstore.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// EventStoreClient is the client interface for EventStore service
type EventStoreClient interface {
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (EventStore_ReadStreamClient, error)
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (EventStore_ReadAllClient, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

// EventStore_ReadStreamClient is the client stream for ReadStream
type EventStore_ReadStreamClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

// EventStore_ReadAllClient is the client stream for ReadAll
type EventStore_ReadAllClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

// EventStoreServer is the server interface for EventStore service
type EventStoreServer interface {
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	ReadStream(*ReadStreamRequest, EventStore_ReadStreamServer) error
	ReadAll(*ReadAllRequest, EventStore_ReadAllServer) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedEventStoreServer()
}

// EventStore_ReadStreamServer is the server stream for ReadStream
type EventStore_ReadStreamServer interface {
	Send(*Event) error
	grpc.ServerStream
}

// EventStore_ReadAllServer is the server stream for ReadAll
type EventStore_ReadAllServer interface {
	Send(*Event) error
	grpc.ServerStream
}

// UnimplementedEventStoreServer provides default implementations
type UnimplementedEventStoreServer struct{}

func (UnimplementedEventStoreServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}

func (UnimplementedEventStoreServer) ReadStream(*ReadStreamRequest, EventStore_ReadStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadStream not implemented")
}

func (UnimplementedEventStoreServer) ReadAll(*ReadAllRequest, EventStore_ReadAllServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadAll not implemented")
}

func (UnimplementedEventStoreServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}

func (UnimplementedEventStoreServer) mustEmbedUnimplementedEventStoreServer() {}

// UnsafeEventStoreServer may be embedded to opt out of forward compatibility
type UnsafeEventStoreServer interface {
	mustEmbedUnimplementedEventStoreServer()
}

// RegisterEventStoreServer registers the server with the gRPC server
func RegisterEventStoreServer(s grpc.ServiceRegistrar, srv EventStoreServer) {
	s.RegisterService(&EventStore_ServiceDesc, srv)
}

// EventStore_ServiceDesc is the service descriptor
var EventStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eventstore.EventStore",
	HandlerType: (*EventStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _EventStore_Append_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _EventStore_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadStream",
			Handler:       _EventStore_ReadStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadAll",
			Handler:       _EventStore_ReadAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eventstore.proto",
}

func _EventStore_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventstore.EventStore/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventstore.EventStore/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

type eventStoreReadStreamServer struct {
	grpc.ServerStream
}

func (x *eventStoreReadStreamServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _EventStore_ReadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStoreServer).ReadStream(m, &eventStoreReadStreamServer{stream})
}

type eventStoreReadAllServer struct {
	grpc.ServerStream
}

func (x *eventStoreReadAllServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _EventStore_ReadAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStoreServer).ReadAll(m, &eventStoreReadAllServer{stream})
}
